apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-llm-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-api
  template:
    metadata:
      labels:
        app: llm-api
    spec:
      containers:
        - name: llm-api
          image: llm-api
          ports:
            - containerPort: 80
          imagePullPolicy: Never
