apiVersion: v1
kind: Service
metadata:
  name: k8-llm-service
spec:
  selector:
    app: llm-api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
